networks:
  alumnio-network:
    ipam:
      driver: default
      config:
        - subnet: 172.130.0.0/16
          gateway: 172.130.0.1

services:
  backend-service:
    build: 
      context: ./backend-service
      dockerfile: Dockerfile

    tty: true
    restart: always

    volumes:
      - /var/alumnio/uploads:/app/uploads

    networks:
      alumnio-network:
        ipv4_address: 172.130.0.2

  frontend-service:
    build: 
      context: ./frontend-service
      dockerfile: Dockerfile

    tty: true
    restart: always

    depends_on:
      - backend-service

    networks:
      alumnio-network:
        ipv4_address: 172.130.0.3

  reverse-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile

    tty: true
    restart: always

    ports:
      - "4000:4000"

    depends_on:
      - backend-service
      - frontend-service
    
    networks:
      alumnio-network:
        ipv4_address: 172.130.0.4